# Administrator password
admin_password: quill

# Websocket configuration
websocket_domain: ipv4.blackjack.literallyshit.net
websocket_port: 8765

# Web server configuration
server_domain: ipv4.blackjack.literallyshit.net
server_port: 8765
server_proxy_port: 8765
server_interface: ""
