# Administrator password
admin_password: <changeme>

# Websocket configuration
websocket_domain: <changeme>
websocket_port: 8765

# Web server configuration
server_domain: <changeme>
server_port: 8765
server_proxy_port: 8765
server_interface: ""
